version: '3.8'

services:
  db:
    image: postgres:15
    container_name: costco-db
    restart: always
    environment:
      POSTGRES_USER: newrps
      POSTGRES_PASSWORD: Pspspsps1234!!
      POSTGRES_DB: costco_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newrps -d costco_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: costco-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
